### ISSUE TITLE
Problem day 3 Bottas

### ISSUE THREAD

**Issue by VentuIlGrande** [Ax6/Fast-F1#7]
I can't see Bottas' data for test day 3, time finds it but speeds don't

**Comment by Ax6** [comment]
Hello, this problem is known and I couldn't find a consistent solution yet. Refer to https://ax6.github.io/Fast-F1/known_bugs.html under "_Day 3 and 6 of winter testing 2020_". You may be able to tweak it by introducing an offset on the Time axis in the telemetry data of Bottas. But this would mean to modify the library.

**Comment by VentuIlGrande** [comment]
Let me know as soon as you can find a solution thanks

**Comment by Ax6** [comment]
After more investigation, it looks like the telemetry data is simply missing. This problem occurs in correspondence of Bottas fastest lap. This might be why it is so easy to notice. I wouldn't be surprised if the issue verifies also in other cases.


![bottas](https://user-images.githubusercontent.com/6977926/75632431-43774e80-5bfc-11ea-9816-b320f738548e.png)

**Comment by Bettiol** [comment]
Same thing Hamilton on Day 6.

PS. Is it possible to have the code to generate the above graph?

Thanks
![Figure_1](https://user-images.githubusercontent.com/36667512/75633291-eb444a80-5c03-11ea-9078-7cc119e5fe72.png)

**Comment by Ax6** [comment]
```python
import fastf1 as ff1
from fastf1 import plotting
from fastf1 import api
from matplotlib import pyplot as plt

tests = ff1.get_session(2020, 'testing', '3')
data = api.car_data(tests.api_path)
# Access driver with its car number
ocon = data['31']
bottas = data['77']

fig, axes = plt.subplots(nrows=3)
for i, ch in enumerate(['Speed', 'RPM', 'Throttle']):
    axes[i].plot(ocon['Date'], ocon[ch],
                 color=plotting.TEAM_COLORS['Renault'])
    axes[i].plot(bottas['Date'], bottas[ch],
                 color=plotting.TEAM_COLORS['Mercedes'])
    axes[i].set_title(ch)
plt.show()
```

Let me know if it is the case for Hamilton as well.

**Comment by Bettiol** [comment]
> ```python
> import fastf1 as ff1
> from fastf1 import plotting
> from fastf1 import api
> from matplotlib import pyplot as plt
> 
> tests = ff1.get_session(2020, 'testing', '3')
> data = api.car_data(tests.api_path)
> # Access driver with its car number
> ocon = data['31']
> bottas = data['77']
> 
> fig, axes = plt.subplots(nrows=3)
> for i, ch in enumerate(['Speed', 'RPM', 'Throttle']):
>     axes[i].plot(ocon['Date'], ocon[ch],
>                  color=plotting.TEAM_COLORS['Renault'])
>     axes[i].plot(bottas['Date'], bottas[ch],
>                  color=plotting.TEAM_COLORS['Mercedes'])
>     axes[i].set_title(ch)
> plt.show()
> ```
> 
> Let me know if it is the case for Hamilton as well.

Yes, same case. 100% Throttle, 0 Speed and constant RPM

![Es](https://user-images.githubusercontent.com/36667512/75634678-116fe780-5c10-11ea-8684-bcec6809be1d.png)

**Comment by Ax6** [comment]
Good to know! Thanks for checking out. Since this is basically the raw data coming from F1 live timing, I don’t think there’s anything we can do.
